trigger:
  branches:
    include:
      - main
      - v*-prep
  tags:
    include:
      - v*

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    displayName: "Install Node.js 15.x"
    inputs:
      versionSpec: "15.x"

  - task: Bash@3
    displayName: "Install Dependencies"
    inputs:
      targetType: "inline"
      script: "yarn"
  
  - task: Bash@3
    continueOnError: true
    displayName: "Lint"
    inputs:
      targetType: "inline"
      script: "yarn lint"
  
  - task: Bash@3
    displayName: "Build"
    continueOnError: true
    inputs:
      targetType: "inline"
      script: "yarn compile"
  
  - task: Bash@3
    displayName: "Run Unit Tests"
    condition: always()
    inputs:
      targetType: "inline"
      script: "./scripts/test-unit.sh -c"

  - task: PublishTestResults@2
    displayName: "Publish Unit Test Results"
    condition: always()
    inputs:
      testRunner: JUnit
      testResultsFiles: '**/test-results.xml'

  - task: PublishCodeCoverageResults@1
    condition: always()
    displayName: "Publish Unit Tests Code Coverage"
    inputs:
      codeCoverageTool: "Cobertura"
      summaryFileLocation: "coverage/cobertura-coverage.xml"

  - task: Bash@3
    displayName: "Run Integration Tests"
    condition: always()
    inputs:
      targetType: "inline"
      script: "./scripts/test-integration.sh -c"

  - task: PublishTestResults@2
    displayName: "Publish Integration Test Results"
    condition: always()
    inputs:
      testRunner: JUnit
      testResultsFiles: '**/test-results.xml'

  - task: PublishCodeCoverageResults@1
    condition: always()
    displayName: "Publish Integration Tests Code Coverage"
    inputs:
      codeCoverageTool: "Cobertura"
      summaryFileLocation: "coverage/cobertura-coverage.xml"

  - task: Bash@3
    displayName: "Run e2e Tests"
    condition: always()
    inputs:
      targetType: "inline"
      script: "./scripts/test-e2e.sh -c"

  - task: PublishTestResults@2
    displayName: "Publish e2e Test Results"
    condition: always()
    inputs:
      testRunner: JUnit
      testResultsFiles: '**/test-results.xml'
